[profile.default]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false


remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@protocol/contracts/=lib/protocol/packages/core/contracts"
]